-- 073: Listening Library
-- Curated listening passages across all 4 test types with comprehension questions

CREATE TABLE IF NOT EXISTS listening_passages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  passage TEXT NOT NULL,                 -- the listening text
  category TEXT NOT NULL,                -- 'academic_lecture', 'campus_conversation', 'business_meeting', 'travel_announcement', 'news_report'
  test_type TEXT DEFAULT 'ALL',          -- TOEFL_IBT, IELTS, TOEIC, ALL
  difficulty TEXT DEFAULT 'intermediate',-- beginner, intermediate, advanced
  cefr_level TEXT DEFAULT 'B1',          -- A1..C2
  duration_seconds INTEGER DEFAULT 60,   -- approximate duration
  voice TEXT DEFAULT 'alloy',            -- TTS voice to use
  source TEXT,                           -- attribution (TED, NPR, BBC, etc.)
  comprehension_questions TEXT,          -- JSON array of {q, options[4], answer_idx, explanation}
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_listening_cat ON listening_passages(category, difficulty);
CREATE INDEX IF NOT EXISTS idx_listening_test ON listening_passages(test_type, category);
CREATE INDEX IF NOT EXISTS idx_listening_cefr ON listening_passages(cefr_level);

CREATE TABLE IF NOT EXISTS listening_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  passage_id INTEGER NOT NULL,
  answers TEXT,                          -- JSON array of {q_idx, selected, correct}
  correct_count INTEGER DEFAULT 0,
  total_count INTEGER DEFAULT 0,
  score_pct INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_listen_attempts_user ON listening_attempts(user_id, created_at);

-- Seed: curated listening passages (15 entries spanning test types + levels)
INSERT INTO listening_passages (title, passage, category, test_type, difficulty, cefr_level, duration_seconds, voice, source, comprehension_questions) VALUES
  ('Office Meeting: Project Deadline', 'Manager: Good morning everyone. Thanks for joining on short notice. I want to discuss the quarterly report deadline. As you know, the board meeting is scheduled for next Friday, October 18th. We need to submit the report by Wednesday at the latest, so that gives us about ten days. Sarah, can you handle the financial section? Sarah: Sure, I will have the draft ready by Monday. Manager: Perfect. John, what about the marketing analysis? John: I will coordinate with the Asia team. Their data should be in by Tuesday. Manager: Great. One more thing — please use the new template that Priya circulated last week. Any questions? Sarah: Should we include the projections for next quarter? Manager: Yes, but keep them conservative. The board does not like overly optimistic numbers.', 'business_meeting', 'TOEIC', 'intermediate', 'B1', 75, 'alloy', 'Original', '[{"q":"When is the board meeting?","options":["October 11th","October 18th","October 25th","November 1st"],"answer_idx":1,"explanation":"Manager says \"the board meeting is scheduled for next Friday, October 18th.\""},{"q":"Who will handle the financial section?","options":["John","Priya","Sarah","The manager"],"answer_idx":2,"explanation":"Manager asks \"Sarah, can you handle the financial section?\""},{"q":"What is the deadline for the report submission?","options":["Monday","Tuesday","Wednesday","Friday"],"answer_idx":2,"explanation":"\"We need to submit the report by Wednesday at the latest.\""},{"q":"What should the projections be like?","options":["Optimistic","Conservative","Detailed","Not included"],"answer_idx":1,"explanation":"Manager says \"keep them conservative.\""}]'),

  ('Campus Announcement: Library Hours', 'Attention students. The main library will have extended hours during finals week. Starting next Monday, the library will open at 7 AM and close at midnight, seven days a week, until the end of the exam period on December 15th. The third floor will be designated as a quiet study area — no talking, no group work, phones on silent. The second floor will be for collaborative work and discussion. Please note that food and drinks are not allowed beyond the ground floor cafe. Also, due to construction, the east entrance will be closed. Please use the west entrance. For students who need 24-hour access, the engineering building computer lab is open all night. Thank you, and good luck on your exams.', 'campus_conversation', 'TOEFL_IBT', 'intermediate', 'B1', 65, 'alloy', 'Original', '[{"q":"How long will the library have extended hours?","options":["One week","Two weeks","About a month","Until January"],"answer_idx":2,"explanation":"\"until the end of the exam period on December 15th\" implies about 4 weeks."},{"q":"What is the rule for the third floor?","options":["Group work allowed","Quiet study only","Open 24 hours","Food allowed"],"answer_idx":1,"explanation":"\"The third floor will be designated as a quiet study area — no talking, no group work.\""},{"q":"Which entrance is closed?","options":["West entrance","Main entrance","East entrance","Ground floor entrance"],"answer_idx":2,"explanation":"\"the east entrance will be closed. Please use the west entrance.\""},{"q":"Where can students go for 24-hour access?","options":["Main library","Student center","Engineering building","Dormitory"],"answer_idx":2,"explanation":"\"the engineering building computer lab is open all night.\""}]'),

  ('Academic Lecture: Photosynthesis', 'Professor: Today we will discuss photosynthesis, the process by which plants convert light energy into chemical energy. The basic equation is simple: carbon dioxide plus water, in the presence of sunlight, produces glucose and oxygen. However, the actual mechanism is far more complex. Photosynthesis occurs in the chloroplasts, specifically in structures called thylakoids. There are two main stages. The first is the light-dependent reactions, which occur in the thylakoid membranes. These reactions capture light energy and use it to produce ATP and NADPH. The second stage is the Calvin cycle, which takes place in the stroma. The Calvin cycle does not require light directly, but it does depend on the products of the light reactions. A key point to remember is that chlorophyll, the green pigment, absorbs light most efficiently in the red and blue wavelengths. That is why plants appear green — they reflect green light rather than absorbing it.', 'academic_lecture', 'TOEFL_IBT', 'advanced', 'B2', 90, 'onyx', 'Original', '[{"q":"Where do the light-dependent reactions occur?","options":["Stroma","Thylakoid membranes","Chloroplast outer layer","Cell wall"],"answer_idx":1,"explanation":"\"The first is the light-dependent reactions, which occur in the thylakoid membranes.\""},{"q":"What is the role of chlorophyll?","options":["Reflects green light","Produces oxygen","Absorbs red and blue light","Generates glucose"],"answer_idx":2,"explanation":"\"chlorophyll... absorbs light most efficiently in the red and blue wavelengths.\""},{"q":"Where does the Calvin cycle take place?","options":["Thylakoids","Stroma","Cell membrane","Vacuole"],"answer_idx":1,"explanation":"\"The Calvin cycle... takes place in the stroma.\""},{"q":"Why do plants appear green?","options":["They produce green pigment","They reflect green light","They absorb green light","They have green water"],"answer_idx":1,"explanation":"\"they reflect green light rather than absorbing it.\""}]'),

  ('Travel Announcement: Train Delay', 'Good morning passengers. This is an announcement for platform 3. The 9:15 express service to Manchester Piccadilly has been delayed by approximately 25 minutes due to a signaling fault at Stockport. We apologize for the inconvenience. Passengers with tickets for the 9:15 service may use these tickets on the 9:45 stopping service, which will depart from the same platform. The 10:30 service to Birmingham New Street is expected to run on time. For passengers traveling to London Euston, the next direct service departs at 10:05 from platform 7. Refreshment vouchers are available from the ticket office for affected passengers. Please speak to a staff member if you require assistance. We will provide further updates as they become available. Thank you for your patience.', 'travel_announcement', 'IELTS', 'intermediate', 'B1', 60, 'alloy', 'Original', '[{"q":"Why is the train delayed?","options":["Bad weather","Signal fault","Staff shortage","Track maintenance"],"answer_idx":1,"explanation":"\"due to a signaling fault at Stockport.\""},{"q":"How long is the delay?","options":["10 minutes","15 minutes","25 minutes","45 minutes"],"answer_idx":2,"explanation":"\"has been delayed by approximately 25 minutes.\""},{"q":"What can passengers with 9:15 tickets do?","options":["Get a refund","Use tickets on 9:45 service","Wait for next train","Travel tomorrow"],"answer_idx":1,"explanation":"\"may use these tickets on the 9:45 stopping service.\""},{"q":"Where do passengers to London go next?","options":["Platform 3 at 9:45","Platform 7 at 10:05","Platform 3 at 10:30","Ticket office"],"answer_idx":1,"explanation":"\"the next direct service departs at 10:05 from platform 7.\""}]'),

  ('News Report: Climate Conference', 'World leaders gathered in Geneva this week for the annual climate summit, with delegates from 196 countries in attendance. The main focus of this year''s talks is on reducing methane emissions, which scientists say could slow global warming more quickly than cutting carbon dioxide. The United States and the European Union have jointly proposed a 30 percent reduction in methane emissions by 2030. China, the world''s largest methane emitter, has not yet committed to a specific target, but said it would announce one by the end of the year. Environmental groups have criticized the slow pace of negotiations, noting that previous commitments have largely gone unmet. However, there is cautious optimism that this summit could produce a binding agreement, unlike the voluntary pledges made in Glasgow two years ago.', 'news_report', 'IELTS', 'advanced', 'B2', 75, 'onyx', 'Original', '[{"q":"What is the main focus of the climate summit?","options":["Carbon dioxide","Methane emissions","Renewable energy","Forest protection"],"answer_idx":1,"explanation":"\"The main focus of this year''s talks is on reducing methane emissions.\""},{"q":"How much methane reduction is being proposed?","options":["10 percent","20 percent","30 percent","50 percent"],"answer_idx":2,"explanation":"\"a 30 percent reduction in methane emissions by 2030.\""},{"q":"Which country has not yet committed to a target?","options":["USA","EU","China","India"],"answer_idx":2,"explanation":"\"China... has not yet committed to a specific target.\""},{"q":"How does this summit differ from Glasgow?","options":["Voluntary pledges","Binding agreement","No delegates","Larger budget"],"answer_idx":1,"explanation":"\"this summit could produce a binding agreement, unlike the voluntary pledges made in Glasgow.\""}]'),

  ('Conversation: Apartment Rental', 'A: Hi, I am calling about the apartment you advertised. Is it still available? B: Yes, it is. The two-bedroom unit on Oak Street. When are you looking to move in? A: I would like to move in by the first of next month, if possible. B: That works. The rent is 1,200 dollars per month, which includes water and trash, but not electricity or internet. A: I see. Are pets allowed? B: We allow cats, but no dogs. The landlord has a strict policy on that. A: No problem, I only have a cat. What about parking? B: There is one parking spot included. Additional vehicles can use the street parking with a permit from the city. A: Great. Can I come by and see the place this weekend? B: Sure. How about Saturday at 2 PM? A: That works perfectly. See you then.', 'campus_conversation', 'ALL', 'beginner', 'A2', 70, 'alloy', 'Original', '[{"q":"What is the rent?","options":["$1,000","$1,200","$1,500","$2,000"],"answer_idx":1,"explanation":"\"The rent is 1,200 dollars per month.\""},{"q":"What is included in the rent?","options":["Everything","Water and trash","Electricity","Internet"],"answer_idx":1,"explanation":"\"includes water and trash, but not electricity or internet.\""},{"q":"What pets are allowed?","options":["Dogs","Cats","Both","None"],"answer_idx":1,"explanation":"\"We allow cats, but no dogs.\""},{"q":"When is the viewing?","options":["Sunday 2 PM","Saturday 2 PM","Saturday 10 AM","Friday 6 PM"],"answer_idx":1,"explanation":"\"How about Saturday at 2 PM?\""}]'),

  ('Academic Lecture: Plate Tectonics', 'Professor: Let us continue our discussion of plate tectonics. As you recall, the Earth''s lithosphere is divided into several large plates that float on the semi-fluid asthenosphere below. There are three main types of plate boundaries. First, divergent boundaries, where plates move apart. Mid-ocean ridges are classic examples — new crust forms as magma rises to fill the gap. Second, convergent boundaries, where plates collide. When an oceanic plate meets a continental plate, the denser oceanic plate subducts beneath the continental plate, forming deep ocean trenches and volcanic mountain ranges like the Andes. Third, transform boundaries, where plates slide past each other horizontally. The San Andreas Fault in California is a famous example. Earthquakes are most common along these boundaries, particularly at transform and convergent zones.', 'academic_lecture', 'TOEFL_IBT', 'advanced', 'C1', 90, 'onyx', 'Original', '[{"q":"How many types of plate boundaries are there?","options":["Two","Three","Four","Five"],"answer_idx":1,"explanation":"\"There are three main types of plate boundaries.\""},{"q":"What happens at a divergent boundary?","options":["Plates collide","Plates slide past each other","Plates move apart","Plates submerge"],"answer_idx":2,"explanation":"\"divergent boundaries, where plates move apart.\""},{"q":"What forms at a convergent oceanic-continental boundary?","options":["Mid-ocean ridges","Volcanic mountain ranges","Deserts","Glaciers"],"answer_idx":1,"explanation":"\"forming deep ocean trenches and volcanic mountain ranges like the Andes.\""},{"q":"Where is the San Andreas Fault?","options":["Japan","California","Italy","Chile"],"answer_idx":1,"explanation":"\"The San Andreas Fault in California is a famous example.\""}]'),

  ('Conversation: Job Interview', 'Interviewer: So, tell me about yourself. Candidate: I am a marketing professional with six years of experience, mostly in digital campaigns. I have managed teams of up to ten people and led projects worth over half a million dollars in ad spend. Interviewer: Impressive. Why do you want to leave your current position? Candidate: I have learned a lot at my current company, but I am looking for a role with more international scope. I speak three languages and I want to use them more. Interviewer: That aligns well with this role. We are expanding into Southeast Asia next year. What would you say is your biggest weakness? Candidate: I tend to be a perfectionist, which sometimes slows me down. I have been working on this by setting clearer deadlines for myself. Interviewer: Good self-awareness. Do you have any questions for us? Candidate: Yes, what does the team structure look like, and who would I report to?', 'campus_conversation', 'TOEFL_IBT', 'intermediate', 'B2', 85, 'alloy', 'Original', '[{"q":"How many years of experience does the candidate have?","options":["Three","Six","Ten","Fifteen"],"answer_idx":1,"explanation":"\"with six years of experience.\""},{"q":"Why does the candidate want to leave?","options":["Low salary","Wants international scope","Bad boss","Needs new skills"],"answer_idx":1,"explanation":"\"I am looking for a role with more international scope.\""},{"q":"What is the candidate''s weakness?","options":["Procrastination","Perfectionism","Impatience","Public speaking"],"answer_idx":1,"explanation":"\"I tend to be a perfectionist.\""},{"q":"Where is the company expanding?","options":["Europe","South America","Southeast Asia","Africa"],"answer_idx":2,"explanation":"\"We are expanding into Southeast Asia next year.\""}]'),

  ('Travel: Airport Announcement', 'Ladies and gentlemen, this is the final boarding call for flight BA 248 to London Heathrow. Passengers should proceed to gate 17 for immediate boarding. Please have your boarding pass and passport ready. Passengers in rows 23 to 35 should use the priority lane. We remind you that only one piece of hand luggage is permitted in the cabin, and any additional bags must be checked at the gate. This flight will close its doors in ten minutes. Thank you for choosing British Airways, and we wish you a pleasant journey.', 'travel_announcement', 'IELTS', 'beginner', 'A2', 50, 'alloy', 'Original', '[{"q":"What is the destination?","options":["Manchester","London Heathrow","Edinburgh","Birmingham"],"answer_idx":1,"explanation":"\"flight BA 248 to London Heathrow.\""},{"q":"What is the gate number?","options":["7","15","17","23"],"answer_idx":2,"explanation":"\"proceed to gate 17 for immediate boarding.\""},{"q":"Which rows use the priority lane?","options":["1 to 10","10 to 22","23 to 35","35 to 50"],"answer_idx":2,"explanation":"\"Passengers in rows 23 to 35 should use the priority lane.\""},{"q":"How long until the doors close?","options":["5 minutes","10 minutes","15 minutes","20 minutes"],"answer_idx":1,"explanation":"\"This flight will close its doors in ten minutes.\""}]'),

  ('News: Tech Industry Layoffs', 'The technology sector continues to face significant challenges, with three major companies announcing layoffs this week alone. Industry analysts say the trend reflects a broader shift as companies adjust to post-pandemic realities and reassess their investments in artificial intelligence. The largest round of cuts came from Meta, which said it would reduce its workforce by approximately 10 percent, affecting around 8,000 employees. Twitter and Amazon have also announced smaller reductions. While these decisions are difficult, the companies argue that restructuring is necessary to remain competitive. However, labor advocates point out that the affected workers include many highly skilled engineers and product managers, whose expertise will be difficult to replace. Some economists warn that continued layoffs in the tech sector could have ripple effects across the broader economy.', 'news_report', 'TOEFL_IBT', 'advanced', 'B2', 70, 'onyx', 'Original', '[{"q":"How many companies announced layoffs this week?","options":["One","Two","Three","Four"],"answer_idx":2,"explanation":"\"with three major companies announcing layoffs this week alone.\""},{"q":"What percentage of Meta will be laid off?","options":["5 percent","8 percent","10 percent","15 percent"],"answer_idx":2,"explanation":"\"reduce its workforce by approximately 10 percent.\""},{"q":"How many employees will Meta cut?","options":["3,000","5,000","8,000","12,000"],"answer_idx":2,"explanation":"\"affecting around 8,000 employees.\""},{"q":"What do labor advocates worry about?","options":["Stock prices","Skilled workers being laid off","AI development","Government regulation"],"answer_idx":1,"explanation":"\"the affected workers include many highly skilled engineers and product managers.\""}]'),

  ('Lecture: Language Acquisition', 'Professor: How do children acquire language so quickly? This is one of the central questions in linguistics. There are two main theories. The behaviorist theory, popularized by B.F. Skinner in the 1950s, argued that children learn language through imitation and reinforcement. Parents say words, children repeat them, and correct usage is rewarded. However, Noam Chomsky challenged this view in the 1960s. He proposed that humans are born with an innate language acquisition device, or LAD, which contains universal grammatical rules. According to Chomsky, this explains why children can produce sentences they have never heard before. Modern researchers generally take a middle ground, acknowledging both innate capacities and environmental input. What is clear is that the critical period for language learning appears to end around puberty, after which acquiring native-like pronunciation becomes much more difficult.', 'academic_lecture', 'IELTS', 'advanced', 'C1', 90, 'onyx', 'Original', '[{"q":"What is the behaviorist theory about?","options":["Innate grammar","Imitation and reinforcement","Universal rules","Genetic programming"],"answer_idx":1,"explanation":"\"children learn language through imitation and reinforcement.\""},{"q":"Who proposed the LAD theory?","options":["Skinner","Chomsky","Piaget","Vygotsky"],"answer_idx":1,"explanation":"\"Noam Chomsky challenged this view in the 1960s.\""},{"q":"What is the LAD?","options":["Learning tool","Innate language device","Test for grammar","Teaching method"],"answer_idx":1,"explanation":"\"humans are born with an innate language acquisition device, or LAD.\""},{"q":"When does the critical period for language end?","options":["Age 5","Age 8","Around puberty","Adulthood"],"answer_idx":2,"explanation":"\"the critical period for language learning appears to end around puberty.\""}]'),

  ('Conversation: Doctor Appointment', 'Patient: Hi doctor, thanks for seeing me on short notice. Doctor: Of course, what seems to be the problem? Patient: I have had a sore throat for about four days now, and it is not getting better. I also have a slight fever. Doctor: Let me take a look. Open your mouth and say ah. Patient: Ahhh. Doctor: Your throat is quite red. I can see some white spots on your tonsils, which suggests a bacterial infection. I am going to prescribe a course of antibiotics, usually 10 days. Patient: Is there anything I can do to feel better in the meantime? Doctor: Yes, drink plenty of fluids, rest as much as possible, and you can take ibuprofen for the pain. If the symptoms get worse, or if you develop a high fever above 39 degrees, come back immediately. Patient: Thank you, doctor. Doctor: You are welcome. The prescription will be ready at the front desk.', 'campus_conversation', 'ALL', 'intermediate', 'B1', 80, 'alloy', 'Original', '[{"q":"How long has the patient had symptoms?","options":["Two days","Four days","One week","Two weeks"],"answer_idx":1,"explanation":"\"I have had a sore throat for about four days now.\""},{"q":"What does the doctor see in the throat?","options":["Ulcers","White spots","Bleeding","Swelling"],"answer_idx":1,"explanation":"\"I can see some white spots on your tonsils.\""},{"q":"What treatment is prescribed?","options":["Surgery","Antibiotics","Rest only","Throat spray"],"answer_idx":1,"explanation":"\"I am going to prescribe a course of antibiotics.\""},{"q":"When should the patient return immediately?","options":["After 3 days","If symptoms worsen","For a checkup","Never"],"answer_idx":1,"explanation":"\"If the symptoms get worse... come back immediately.\""}]'),

  ('Lecture: Microeconomics Supply', 'Professor: Today we cover the law of supply. The law of supply states that, all else being equal, as the price of a good rises, the quantity supplied also rises. This relationship is usually positive. Why? Because higher prices mean higher potential profits, which incentivize producers to manufacture more. There are exceptions. Some goods, like original works of art, cannot be produced in larger quantities no matter how high the price goes. Economists call these fixed-supply goods. The supply curve is typically upward-sloping. However, the position of the curve can shift due to changes in input costs, technology, or the number of sellers. For example, if raw material prices fall, supply increases at every price level, shifting the curve to the right. This is different from a movement along the curve, which represents a change in quantity supplied in response to a price change.', 'academic_lecture', 'TOEFL_IBT', 'advanced', 'C1', 95, 'onyx', 'Original', '[{"q":"What does the law of supply state?","options":["Higher price = lower supply","Higher price = higher supply","Price does not affect supply","Supply is constant"],"answer_idx":1,"explanation":"\"as the price of a good rises, the quantity supplied also rises.\""},{"q":"What is an example of fixed-supply goods?","options":["Cars","Original works of art","Food","Clothing"],"answer_idx":1,"explanation":"\"Some goods, like original works of art, cannot be produced in larger quantities.\""},{"q":"What causes the supply curve to shift right?","options":["Higher prices","Lower raw material costs","Fewer sellers","Less technology"],"answer_idx":1,"explanation":"\"if raw material prices fall, supply increases... shifting the curve to the right.\""},{"q":"What is a movement along the curve?","options":["Change in input costs","Change in quantity supplied","Change in technology","Change in sellers"],"answer_idx":1,"explanation":"\"a movement along the curve... represents a change in quantity supplied.\""}]'),

  ('Conversation: Restaurant Order', 'Waiter: Are you ready to order? Customer: Yes, I will have the grilled salmon, please. Waiter: How would you like it cooked? Customer: Medium, please. And can I have a side of vegetables instead of fries? Waiter: Of course. Would you like something to drink? Customer: Just water, sparkling if you have it. Waiter: Sparkling or still? Customer: Sparkling, please. Waiter: Anything to start with? Perhaps the soup of the day? Customer: What is it today? Waiter: Cream of mushroom. Customer: That sounds good. I will have a bowl. Waiter: Excellent. I will be right back with your drinks and the soup.', 'campus_conversation', 'ALL', 'beginner', 'A1', 50, 'alloy', 'Original', '[{"q":"What is the main course?","options":["Steak","Grilled salmon","Pasta","Chicken"],"answer_idx":1,"explanation":"\"I will have the grilled salmon, please.\""},{"q":"How does the customer want the salmon cooked?","options":["Rare","Medium","Well done","He does not specify"],"answer_idx":1,"explanation":"\"Medium, please.\""},{"q":"What side does the customer want?","options":["Fries","Rice","Vegetables","Salad"],"answer_idx":2,"explanation":"\"can I have a side of vegetables instead of fries?\""},{"q":"What kind of water does the customer order?","options":["Still","Sparkling","Tap","Mineral"],"answer_idx":1,"explanation":"\"Sparkling, please.\""}]'),

  ('News: Renewable Energy Growth', 'Renewable energy sources accounted for a record 30 percent of global electricity generation last year, according to a new report by the International Energy Agency. Solar and wind power led the growth, with capacity additions reaching all-time highs. The shift has been driven by falling costs, government subsidies, and growing concerns about climate change. China remains the largest installer of renewable energy, accounting for nearly half of new solar capacity worldwide. However, the report warns that current progress is still insufficient to meet the targets set in the Paris Agreement. To limit global warming to 1.5 degrees Celsius, renewable capacity must triple by 2030. The IEA also noted that grid infrastructure and energy storage remain significant bottlenecks, particularly in developing countries.', 'news_report', 'IELTS', 'advanced', 'B2', 75, 'onyx', 'Original', '[{"q":"What percentage of electricity came from renewables last year?","options":["10 percent","20 percent","30 percent","50 percent"],"answer_idx":2,"explanation":"\"Renewable energy sources accounted for a record 30 percent of global electricity.\""},{"q":"Which country leads in renewable installation?","options":["USA","Germany","China","India"],"answer_idx":2,"explanation":"\"China remains the largest installer of renewable energy.\""},{"q":"By how much must renewable capacity grow by 2030?","options":["Double","Triple","Quadruple","Stay the same"],"answer_idx":1,"explanation":"\"renewable capacity must triple by 2030.\""},{"q":"What is a major bottleneck in developing countries?","options":["Solar panels","Wind turbines","Grid infrastructure","Government policy"],"answer_idx":2,"explanation":"\"grid infrastructure and energy storage remain significant bottlenecks.\""}]');
