-- 075: Video Comprehension
-- Curated YouTube videos for English learning with key vocab + comprehension questions

CREATE TABLE IF NOT EXISTS video_lessons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  youtube_id TEXT NOT NULL,             -- the video ID portion of the URL
  description TEXT,
  category TEXT NOT NULL,               -- 'ted_talk', 'news_clip', 'lecture', 'interview', 'documentary'
  topic TEXT,                           -- e.g. 'climate', 'technology', 'psychology'
  test_type TEXT DEFAULT 'ALL',         -- TOEFL_IBT, IELTS, TOEIC, ALL
  difficulty TEXT DEFAULT 'intermediate',
  cefr_level TEXT DEFAULT 'B1',
  duration_seconds INTEGER DEFAULT 300,
  channel TEXT,                        -- e.g. 'TED', 'BBC Learning English', 'VOA Learning English'
  key_vocabulary TEXT,                 -- JSON array of {word, definition_id}
  comprehension_questions TEXT,        -- JSON array of {q, options[4], answer_idx, explanation, timestamp}
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_vl_cat ON video_lessons(category, difficulty);
CREATE INDEX IF NOT EXISTS idx_vl_test ON video_lessons(test_type, category);
CREATE INDEX IF NOT EXISTS idx_vl_cefr ON video_lessons(cefr_level);

CREATE TABLE IF NOT EXISTS video_views (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  video_id INTEGER NOT NULL,
  answers TEXT,                        -- JSON array of {q_idx, selected, correct}
  correct_count INTEGER DEFAULT 0,
  total_count INTEGER DEFAULT 0,
  score_pct INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_vv_user ON video_views(user_id, created_at);

-- Seed: 12 curated educational videos
INSERT INTO video_lessons (title, youtube_id, description, category, topic, test_type, difficulty, cefr_level, duration_seconds, channel, key_vocabulary, comprehension_questions) VALUES
  ('The Power of Vulnerability', 'iCvmsMzlF7o', 'Brené Brown on vulnerability and connection', 'ted_talk', 'psychology', 'TOEFL_IBT', 'intermediate', 'B2', 1200, 'TED',
   '[{"word":"vulnerability","definition":"the state of being open to emotional harm"},{"word":"shame","definition":"a painful feeling of humiliation"},{"word":"authenticity","definition":"the quality of being genuine"},{"word":"connection","definition":"a relationship in which people feel close"}]',
   '[{"q":"What does the speaker say vulnerability is?","options":["A weakness","The birthplace of innovation and creativity","An unnecessary risk","A personality flaw"],"answer_idx":1,"explanation":"Brené says \"vulnerability is the birthplace of innovation, creativity, and change.\""},{"q":"What did the research find about numbing emotions?","options":["It works well","It numbs both positive and negative","It only numbs negative","It is healthy"],"answer_idx":1,"explanation":"She says we cannot selectively numb emotions — numbing negative also numbs joy."},{"q":"What word does she use to describe people who have a strong sense of love?","options":["Brave","Wholehearted","Lucky","Smart"],"answer_idx":1,"explanation":"She says \"wholehearted\" people have strong sense of love and belonging."},{"q":"What is her conclusion?","options":["Avoid risk at all costs","Pretend you are not vulnerable","Lean into vulnerability","Hide your emotions"],"answer_idx":2,"explanation":"She concludes that we should \"lean into\" discomfort and vulnerability."}]'),

  ('How Great Leaders Inspire Action', 'qp0HIF3SfI4', 'Simon Sinek on starting with why', 'ted_talk', 'leadership', 'ALL', 'intermediate', 'B1', 1100, 'TED',
   '[{"word":"inspire","definition":"to fill with the urge to do something"},{"word":"manipulation","definition":"controlling someone for personal gain"},{"word":"loyalty","definition":"a strong feeling of support"},{"word":"vision","definition":"the ability to think about the future"}]',
   '[{"q":"What does Sinek say most organizations do wrong?","options":["They start with what","They start with how","They start with who","They start with when"],"answer_idx":0,"explanation":"He says most companies communicate starting with WHAT, then HOW, then WHY — backwards."},{"q":"What is the golden circle?","options":["Why-How-What","What-How-Why","Who-What-Where","Goal-Strategy-Tactic"],"answer_idx":0,"explanation":"The Golden Circle is Why → How → What."},{"q":"According to Sinek, why do people buy from certain companies?","options":["Price","Quality","They believe in the why","Convenience"],"answer_idx":2,"explanation":"People buy from those who believe what they believe — alignment of WHY."},{"q":"What example does he use?","options":["Apple","Walmart","McDonalds","Tesla"],"answer_idx":0,"explanation":"He uses Apple as the primary example of a company that starts with WHY."}]'),

  ('The Puzzle of Motivation', 'wdgKA3BlSBI', 'Dan Pink on what drives us', 'ted_talk', 'psychology', 'TOEFL_IBT', 'advanced', 'B2', 1300, 'TED',
   '[{"word":"motivation","definition":"the reason for acting"},{"word":"autonomy","definition":"freedom to choose"},{"word":"mastery","definition":"high level of skill"},{"word":"purpose","definition":"a meaningful goal"}]',
   '[{"q":"What are the three elements of true motivation?","options":["Money, fame, power","Autonomy, mastery, purpose","Fear, hope, love","Speed, accuracy, effort"],"answer_idx":1,"explanation":"Pink identifies autonomy, mastery, and purpose as the three pillars."},{"q":"What does Pink say about extrinsic rewards?","options":["They always work","They often backfire for complex tasks","They are the only way","They are the best approach"],"answer_idx":1,"explanation":"He cites research showing extrinsic rewards hurt performance on complex, creative tasks."},{"q":"What example does he use?","options":["Rodeo clowns and kidney patients","Lawyers and teachers","Engineers and doctors","Salespeople and marketers"],"answer_idx":0,"explanation":"Pink uses the surprising example of MIT students who became better artists when offered lower pay."},{"q":"What is the \"20th century operating system\"?","options":["Carrots and sticks","Software updates","Hierarchies","Email systems"],"answer_idx":0,"explanation":"He calls \"if-then\" rewards (carrots and sticks) the outdated 20th century OS."}]'),

  ('Your Body Language May Shape Who You Are', 'Ks-_Mh1QhMc', 'Amy Cuddy on power posing', 'ted_talk', 'psychology', 'IELTS', 'intermediate', 'B2', 1260, 'TED',
   '[{"word":"nonverbal","definition":"not using words"},{"word":"posture","definition":"the way someone stands or sits"},{"word":"confidence","definition":"a feeling of self-assurance"},{"word":"intervention","definition":"an action to improve a situation"}]',
   '[{"q":"What does Cuddy say nonverbals do?","options":["Just express feelings","Govern how we feel and think","Are unimportant","Only matter for leaders"],"answer_idx":1,"explanation":"She says nonverbals govern how we think and feel, not just how we express."},{"q":"What is a power pose?","options":["Sitting still","Standing up tall and open","Crossing your arms","Looking down"],"answer_idx":1,"explanation":"Power poses are expansive, open postures that take up space."},{"q":"What hormones change with power posing?","options":["Dopamine and serotonin","Testosterone and cortisol","Adrenaline and insulin","Oxytocin and melatonin"],"answer_idx":1,"explanation":"Power poses increase testosterone (dominance) and decrease cortisol (stress)."},{"q":"How long should you hold a power pose?","options":["5 seconds","30 seconds","2 minutes","30 minutes"],"answer_idx":2,"explanation":"Cuddy recommends holding power poses for 2 minutes before stressful events."}]'),

  ('BBC Learning English: 6 Minute English', 'Various', 'BBC 6 Minute English episodes', 'interview', 'general', 'ALL', 'intermediate', 'B1', 360, 'BBC Learning English',
   '[{"word":"contemporary","definition":"belonging to the same time period"},{"word":"resilient","definition":"able to recover quickly"},{"word":"notion","definition":"an idea or belief"}]',
   '[{"q":"What format does the BBC 6 Minute English use?","options":["Solo monologue","Two-host discussion with vocabulary","News report","Interview with celebrity"],"answer_idx":1,"explanation":"Each episode has a host and a guest discussing a topic, with vocabulary explanations."},{"q":"What is the typical length?","options":["1 minute","6 minutes","15 minutes","30 minutes"],"answer_idx":1,"explanation":"The show is named for its 6-minute length."},{"q":"What level is this content suitable for?","options":["Beginner (A1-A2)","Intermediate (B1-B2)","Native speakers only","Children only"],"answer_idx":1,"explanation":"BBC 6 Minute English targets B1-B2 learners."}]'),

  ('Climate Change: The Facts', 'Various', 'BBC documentary on climate change', 'documentary', 'climate', 'IELTS', 'advanced', 'B2', 2700, 'BBC',
   '[{"word":"emissions","definition":"gases released into the atmosphere"},{"word":"biodiversity","definition":"variety of plant and animal life"},{"word":"sustainability","definition":"ability to maintain over time"},{"word":"catastrophic","definition":"causing great damage"}]',
   '[{"q":"What is the main cause of recent climate change?","options":["Natural cycles","Human activity","Solar flares","Volcanic activity"],"answer_idx":1,"explanation":"The documentary emphasizes human greenhouse gas emissions as the main driver."},{"q":"What does the documentary say about biodiversity?","options":["It is increasing","It is stable","It is declining rapidly","It is irrelevant"],"answer_idx":2,"explanation":"It highlights a rapid decline in biodiversity worldwide."},{"q":"What does \"net zero\" mean?","options":["Zero energy use","Balancing emissions produced with those removed","No factories","All renewable"],"answer_idx":1,"explanation":"Net zero means balancing emissions produced with those removed from the atmosphere."},{"q":"What does David Attenborough emphasize?","options":["The problem is exaggerated","The window for action is closing","Technology will save us","We have plenty of time"],"answer_idx":1,"explanation":"Attenborough emphasizes the urgency of the climate crisis."}]'),

  ('How to Learn Any Language in Six Months', 'dUNyMzzy3-4', 'Chris Lonsdale on rapid language learning', 'ted_talk', 'language_learning', 'ALL', 'beginner', 'A2', 1100, 'TEDx',
   '[{"word":"fluent","definition":"able to speak smoothly"},{"word":"immersion","definition":"full surrounding in a language"},{"word":"technique","definition":"a method or skill"}]',
   '[{"q":"What is the first key to language learning?","options":["Memorize grammar rules","Focus on language you can already understand","Use only textbooks","Travel to the country"],"answer_idx":1,"explanation":"Lonsdale stresses focusing on comprehensible input — language you can mostly understand."},{"q":"What does he mean by \"language parent\"?","options":["A native speaker parent","A friendly teacher who corrects you","Your real parent","A dictionary"],"answer_idx":1,"explanation":"A language parent is a supportive person who helps you practice without pressure."},{"q":"What does \"physiology\" refer to in his talk?","options":["Brain chemistry only","Body posture and breathing","Genetics","Sleep cycles"],"answer_idx":1,"explanation":"He says good pronunciation comes from relaxed face muscles, good posture, and proper breathing."},{"q":"How long does he say it takes to become fluent with the right method?","options":["10 years","6 months","1 year","5 years"],"answer_idx":1,"explanation":"The talk title and his claim is 6 months to conversational fluency."}]'),

  ('The Science of Well-Being', 'z-iLR4R9hVI', 'Yale course introduction on well-being', 'lecture', 'psychology', 'TOEFL_IBT', 'intermediate', 'B2', 1800, 'Yale Courses',
   '[{"word":"happiness","definition":"a state of well-being"},{"word":"misconception","definition":"a wrong belief"},{"word":"gratitude","definition":"thankfulness"}]',
   '[{"q":"What does the professor say is a common misconception?","options":["Money buys happiness","Achievement always leads to happiness","We often misidentify what makes us happy","Friends don''t matter"],"answer_idx":2,"explanation":"The course explores how our minds misjudge what will make us happy."},{"q":"What is one of the \"rewirements\"?","options":["Sleep 12 hours daily","Daily gratitude journaling","Avoid all social media","Quit your job"],"answer_idx":1,"explanation":"The course teaches students to practice gratitude and other rewirements."},{"q":"What is \"mis-wanting\"?","options":["Wanting the wrong things","Not wanting anything","Buying too much","Wasting time"],"answer_idx":0,"explanation":"Mis-wanting is our tendency to want things that don''t actually make us happy."}]'),

  ('The Power of Time Off', 'Various', 'Why rest is essential for productivity', 'ted_talk', 'productivity', 'TOEFL_IBT', 'intermediate', 'B2', 900, 'TED',
   '[{"word":"burnout","definition":"exhaustion from overwork"},{"word":"recovery","definition":"return to a normal state"},{"word":"creativity","definition":"the ability to create"}]',
   '[{"q":"What is the central argument?","options":["Work harder, not smarter","Taking time off is essential for peak performance","Vacations are a waste","Most people are lazy"],"answer_idx":1,"explanation":"The talk argues that strategic rest improves performance."},{"q":"What is the relationship between rest and creativity?","options":["Rest kills creativity","Rest fuels creativity","No relationship","Only for artists"],"answer_idx":1,"explanation":"The speaker says that the most creative insights often come during rest."},{"q":"What cultural change does he propose?","options":["Work 24/7","Normalize rest and recovery","Reduce sleep","More deadlines"],"answer_idx":1,"explanation":"He advocates for cultural change to view rest as productive."}]'),

  ('The Hidden Power of Smiling', 'Various', 'The science behind smiling', 'ted_talk', 'psychology', 'IELTS', 'beginner', 'A2', 1100, 'TEDx',
   '[{"word":"genuine","definition":"real or authentic"},{"word":"perception","definition":"the way something is understood"},{"word":"interaction","definition":"communication between people"}]',
   '[{"q":"What is the main point of this talk?","options":["Smiling is fake","Smiling has measurable effects on perception and health","Smiling is unprofessional","Only children should smile"],"answer_idx":1,"explanation":"The talk argues smiling has real, measurable effects on how others perceive us and our own health."},{"q":"What did the study with yearbook photos find?","options":["Smilers were less successful","Smilers had better life outcomes","No difference","Smilers were less healthy"],"answer_idx":1,"explanation":"The researcher found that people who smiled more in yearbook photos tended to have happier, longer lives."},{"q":"Does the speaker recommend faking a smile?","options":["Yes, always","No, find authentic reasons","Only at work","Never smile"],"answer_idx":1,"explanation":"He recommends finding genuine reasons to smile, but acknowledges the physical act itself has benefits."}]'),

  ('AI and the Future of Work', 'Various', 'How AI is changing employment', 'ted_talk', 'technology', 'TOEFL_IBT', 'advanced', 'C1', 1500, 'TED',
   '[{"word":"automation","definition":"use of machines to replace human work"},{"word":"displacement","definition":"the act of moving something from its usual place"},{"word":"reskill","definition":"to learn new skills"}]',
   '[{"q":"What does the speaker predict?","options":["All jobs will disappear","AI will transform, not eliminate, most jobs","Only blue-collar work will change","Nothing will change"],"answer_idx":1,"explanation":"Most experts predict transformation rather than mass elimination."},{"q":"Which skills does the speaker say will remain valuable?","options":["Memorization and repetition","Creativity, empathy, and complex problem-solving","Typing speed","Manual dexterity"],"answer_idx":1,"explanation":"Soft skills like creativity and empathy are hard to automate."},{"q":"What does he recommend workers do?","options":["Resist AI","Embrace lifelong learning","Quit their jobs","Only do manual work"],"answer_idx":1,"explanation":"He recommends continuous reskilling and embracing new tools."},{"q":"What is a key risk of AI?","options":["Too expensive","Bias in algorithms","Slow processing","Limited storage"],"answer_idx":1,"explanation":"The speaker emphasizes algorithmic bias as a major concern."}]'),

  ('The Surprising Science of Happiness', 'Various', 'What research reveals about well-being', 'ted_talk', 'psychology', 'ALL', 'intermediate', 'B2', 1200, 'TED',
   '[{"word":"serotonin","definition":"a brain chemical linked to mood"},{"word":"mindfulness","definition":"awareness of the present moment"},{"word":"resilience","definition":"ability to recover from setbacks"}]',
   '[{"q":"What is one surprising finding about money and happiness?","options":["Money is everything","Above a certain level, more money doesn''t help much","Money is bad","Only rich people are happy"],"answer_idx":1,"explanation":"Research shows that above a certain income level, more money does not significantly increase happiness."},{"q":"What does the speaker recommend for daily life?","options":["Buy more things","Practice gratitude and connection","Work longer hours","Avoid other people"],"answer_idx":1,"explanation":"Daily practices like gratitude and meaningful connection boost well-being."}]');
